### ISSUE TITLE
Create PR Gating Workflow

### ISSUE THREAD

**Issue by dsayling** [dsayling/pydantic-custom-types#3]
Repo needs a CI workflow that will run formatting, linting and unittest checks.

```yaml
name: CI Checks
on:
  pull_request

jobs:
  pre_merge:
    runs_on: ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
        cache: 'poetry'
      - run: poetry install
      - run: |
           # poetry run poe lint
           poetry run poe ruff .
```

I'll create a separate issue for poe
